name: lutho 39
on:
  merge_group:
  pull_request:
    branches: [ main, testing ]
  push:
    branches:
      - main
      - testing
  schedule:
    - cron: '41 16 * * *'  # 16:41 UTC everyday
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      brand_name: lutho
      fedora_version: 39
